### ISSUE TITLE
Seems to fail with typescript@4.0.3

### ISSUE THREAD

**Issue by Gozala** [andoshin11/typescript-error-reporter-action#13]
```
Loaded typescript@4.0.3 from CDN.
(node:2728) UnhandledPromiseRejectionWarning: TypeError: (e || "").replace is not a function
    at /home/runner/work/_actions/andoshin11/typescript-error-reporter-action/v1.0.2/dist/index.js:16:2442770
    at o.toString (/home/runner/work/_actions/andoshin11/typescript-error-reporter-action/v1.0.2/dist/index.js:16:2442832)
    at i (/home/runner/work/_actions/andoshin11/typescript-error-reporter-action/v1.0.2/dist/index.js:16:2442199)
    at Object.n.issue (/home/runner/work/_actions/andoshin11/typescript-error-reporter-action/v1.0.2/dist/index.js:16:2442259)
    at l (/home/runner/work/_actions/andoshin11/typescript-error-reporter-action/v1.0.2/dist/index.js:16:4067317)
    at Object.n.setFailed (/home/runner/work/_actions/andoshin11/typescript-error-reporter-action/v1.0.2/dist/index.js:16:4068058)
    at /home/runner/work/_actions/andoshin11/typescript-error-reporter-action/v1.0.2/dist/index.js:16:4043297
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

https://github.com/multiformats/js-multiformats/runs/1232701675

**Comment by samjhill** [comment]
also happens to me

**Comment by Gozala** [comment]
@samjhill I end up making bunch of improvements to support ts@4.0 specifically:

- Support for 4.0
- Use TS from dependencies instead of fetching one from cdn
- Project path support (for mono repos)
- Support for [TS project references](https://www.typescriptlang.org/docs/handbook/project-references.html)

@andoshin11 I'm happy to send pull requests to try and get those changes inn if you're interested. Have note done so, mostly because I end up taking a different approach by getting rid of CDN piece.

**Comment by quantizor** [comment]
@Gozala you're welcome to make them against my fork: https://github.com/probablyup/typescript-error-reporter-action

**Comment by MarkLyck** [comment]
This is still failing with "typescript": "4.1.3" @andoshin11 any update on this?

**Comment by jimmy927** [comment]
> @samjhill I end up making bunch of improvements to support ts@4.0 specifically:
> 
> * Support for 4.0
> * Use TS from dependencies instead of fetching one from cdn
> * Project path support (for mono repos)
> * Support for [TS project references](https://www.typescriptlang.org/docs/handbook/project-references.html)
> 
> @andoshin11 I'm happy to send pull requests to try and get those changes inn if you're interested. Have note done so, mostly because I end up taking a different approach by getting rid of CDN piece.

I tried to use your fork, like this:

```
name: Typescript Error Reporter
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Typecheck
        uses: probablyup/typescript-error-reporter-action@51b148277c8bafa44b673277b412e98187769daf

```

But i am getting this error:

```
Run probablyup/typescript-error-reporter-action@51b148277c8bafa44b673277b412e98187769daf
Error: Error: no lock file found.
```

Any ideas ?
