### ISSUE TITLE
Does not post a comment with error

### ISSUE THREAD

**Issue by karambirov** [andoshin11/typescript-error-reporter-action#16]
I've set up a workflow for my project. So when an error occurs CI prints the error to the console but a comment in PR conversation doesn't appear like on your screenshot.

What should I do to have comments with errors in PRs?

My workflow file:
```yaml
name: Node CI

on: push

jobs:
  typescript-error-reporter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: TypeScript Error Reporter
        uses: andoshin11/typescript-error-reporter-action@v1.0.2
```
